### ISSUE TITLE
[ATV2] Echo from TV speakers when a Bluetooth (A2DP) headset is connected

### ISSUE THREAD

**Issue by SesioN** [CiNcH83/sony_atv#71]
Pairing and connecting a Bluetooth (A2DP) headset leads to a clear echo on the TV speakers.

[Note]
This is ATV2 related as the feature is not available on ATV1 based TVs.

**Comment by CiNcH83** [comment]
Hi @SesioN 

I value your contribution but please do not enter bugs yourself. Unfortunately I can't control it due to the free GitHub account.

These are the 2 main reasons:

- This is a Sony ATV1 bug tracker, so only for the platform which Sony TVs from 2015 and early 2016 are based on. Most bugs in this tracker also apply to your ATV2 model but I can't verify some of your bugs on my ATV1 (like this A2DP problem). And I really want to make sure myself that all problems in here are for real.

- The only small chance that bugs will actually get fixed by Sony is that this place does not become a forum for all people placing their individual problems here (I know for a fact that this problem is for real even though I don't understand why people want to have sound coming out of speakers and headphonses in parallel).

**Comment by CiNcH83** [comment]
Fixed as of ATV2 FW 6.2858.
